version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8080"
      - "50000:50000"
    volumes:
      - "/home/ec2-user/jenkins_data:/var/jenkins_home"
    networks:
      - net
networks:
  net:
  

