version: '3'

services:

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - "/home/ec2-user/nexus-data:/nexus-data"