version: '3'

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    restart: unless-stopped
    depends_on:
      - sonardb
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - "/opt/sonarqube/conf:/opt/sonarqube/conf"
      - "/opt/sonarqube/data:/opt/sonarqube/data"
      - "/opt/sonarqube/extensions:/opt/sonarqube/extensions"
      - "/opt/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins"
      - "/opt/sonarqube/logs:/opt/sonarqube/logs"
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - net

  sonardb:
    container_name: sonardb
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    volumes:
      - "/var/lib/postgresql:/var/lib/postgresql"
      - "/var/lib/postgresql/data:/var/lib/postgresql/data"
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - net

volumes:
    postgresql_data:
    sonarqube_bundled-plugins:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_db:
    sonarqube_extensions:

networks:
    net:
      driver: bridge